### ISSUE TITLE
I want the window to be transparent or hidden, and the controls to be unaffected

### ISSUE THREAD

**Issue by rcnn-retall** [kivy/kivy#8951]
**Software Versions**
* Python: 3.11.5
* Window:Windows 11 
* Kivy: 2.3.0
* Kivy installation method:conda install kivy

**Describe the bug**
I want to leave the window undisplayed and then the controls above can be clearly visible
I've tried a lot of things and it hasn't worked

The issue tracker is a tool to address **bugs only** (search known bugs: https://git.io/vM1iE).
Please use the #support Discord channel at https://chat.kivy.org/ or Stack Overflow for
support questions, more information at https://git.io/vM1yQ.

**Expected behavior**
I set the window to be transparent, but the controls are also transparent

**To Reproduce**
A short, *runnable* example that reproduces the issue with *latest kivy master*.

**Code and
![ad602bd55610d8357a1cd8b9eaacaeb6](https://github.com/user-attachments/assets/c40c7581-abd5-4c6a-9c38-a4dbe7a6f771)
 Logs and screenshots**

```python
from kivy.uix.screenmanager import Screen
from kivy.core.window import Window
from kivy.app import App
from kivy.uix.button import Button


class STRet_(App):
    def __init__(self):
        super(STRet_, self).__init__()
        Window.opacity = .2
        self.body = Button(text="iewv", size_hint=(.2,.1))
        self.body.opacity =1
    def build(self):
        return self.body

STRet_().run()
```

**Additional context**
There is no way to not display the window, but the controls on the window can be displayed. Or remove the background color of the window.

```[tasklist]
### Tasks
- [ ] https://github.com/kivy/kivy/issues/7211
```

```[tasklist]
### Tasks
- [ ] https://github.com/kivy/kivy/issues/8811
- [ ] https://github.com/kivy/kivy/issues/7211
```

**Comment by ElliotGarbus** [comment]
Opacity impacts the widget (or in this case the Window, and all of it's children.  As described here: https://kivy.org/doc/stable/api-kivy.uix.widget.html#kivy.uix.widget.Widget.opacity

You can use a shaped window to create transparent areas in a borderless Window. Here is an example:
```python
from kivy.config import Config
Config.set('graphics', 'shaped', 1)

# the default Window shape is the Kivy Logo

from kivy.app import App
from kivy.lang import Builder
from kivy.core.window import Window

kv = '''
#:import win kivy.core.window.Window

BoxLayout:
    ToggleButton:
        group: 'colorkey'
        text: '1, 1, 1, 1'
        state: 'down'
        allow_no_selection: False
        on_release: win.shape_color_key = [1, 1, 1, 1]
    ToggleButton:
        group: 'colorkey'
        text: '0, 0, 0, 1'
        allow_no_selection: False
        on_release: win.shape_color_key = [0, 0, 0, 1]
'''


class ShapedWindow(App):
    def build(self):
        Window.shape_mode = 'colorkey'
        return Builder.load_string(kv)


if __name__ == '__main__':
    ShapedWindow().run()
```

**Comment by rcnn-retall** [comment]
> Opacity 会影响 widget（或者在本例中为 Window 及其所有子项）。如下所述：https://kivy.org/doc/stable/api-kivy.uix.widget.html#kivy.uix.widget.Widget.opacity
> 
> 您可以使用形状窗口在无边框 Window 中创建透明区域。下面是一个示例：
> 
> ```python
> from kivy.config import Config
> Config.set('graphics', 'shaped', 1)
> 
> # the default Window shape is the Kivy Logo
> 
> from kivy.app import App
> from kivy.lang import Builder
> from kivy.core.window import Window
> 
> kv = '''
> #:import win kivy.core.window.Window
> 
> BoxLayout:
>     ToggleButton:
>         group: 'colorkey'
>         text: '1, 1, 1, 1'
>         state: 'down'
>         allow_no_selection: False
>         on_release: win.shape_color_key = [1, 1, 1, 1]
>     ToggleButton:
>         group: 'colorkey'
>         text: '0, 0, 0, 1'
>         allow_no_selection: False
>         on_release: win.shape_color_key = [0, 0, 0, 1]
> '''
> 
> 
> class ShapedWindow(App):
>     def build(self):
>         Window.shape_mode = 'colorkey'
>         return Builder.load_string(kv)
> 
> 
> if __name__ == '__main__':
>     ShapedWindow().run()
> ```

gratitude

**Comment by rcnn-retall** [comment]
How do I control this shape

**Comment by ElliotGarbus** [comment]
You can set the shape in the config.  Create a file in an image editor.  In the code below the file is named "test.png"

```python
from kivy.config import Config
Config.set('graphics', 'shaped', 1)
Config.set('graphics', 'height', 512)  # the size must match the image size
Config.set('graphics', 'width', 512)
Config.set('kivy', 'window_shape', 'test.png')  # set image for window shape


from kivy.app import App
from kivy.lang import Builder
from kivy.core.window import Window

kv = '''
#:import win kivy.core.window.Window

BoxLayout:
    ToggleButton:
        group: 'colorkey'
        text: '1, 1, 1, 1'
        state: 'down'
        allow_no_selection: False
        on_release: win.shape_color_key = [1, 1, 1, 1]
    ToggleButton:
        group: 'colorkey'
        text: '0, 0, 0, 1'
        allow_no_selection: False
        on_release: win.shape_color_key = [0, 0, 0, 1]
'''


class ShapedWindow(App):
    def build(self):
        Window.size = 512, 512
        Window.shape_mode = 'colorkey'
        Window.shape_color_key = [1, 1, 1, 1]
        return Builder.load_string(kv)

if __name__ == '__main__':
    ShapedWindow().run()
```
Here is the image I created:
![image](https://github.com/user-attachments/assets/d118aebc-fdc1-472b-a841-962686893035)
Below is the result.  The forest background is the wallpaper on my computer. 
![image](https://github.com/user-attachments/assets/4dbc6532-3aaa-4083-ba4d-ff2f1e9f1911)
![image](https://github.com/user-attachments/assets/30336009-ce27-418a-abe3-8973976651aa)

**Comment by rcnn-retall** [comment]
I don't know why I can't set it up
![6 KXS 5ONZV(E6~(55W~NQA](https://github.com/user-attachments/assets/44749df0-85ba-4665-8232-86cd3f1b7c5e)

**Comment by rcnn-retall** [comment]
![image](https://github.com/user-attachments/assets/873d37d3-b13f-4c27-ab2c-c7a83f0b2103)

**Comment by rcnn-retall** [comment]
@ElliotGarbus You can't set a shape by not having pixels
![1](https://github.com/user-attachments/assets/9106be3c-5e44-4832-8639-ea23012ca580)
Like this

**Comment by rcnn-retall** [comment]
I want to write a desktop pet

**Comment by ElliotGarbus** [comment]
@rcnn-retall You must have all of your Config.set calls prior to importing any additional kivy files.  Many of the kivy files read the config settings on import.  This is why you must set the Config first.  

I'm assuming, "You can't set a shape by not having pixels", means you can set the shape using a transparent area.  You could take your image into an image editor and set the transparent areas to a solid color (black for example), and use that to set the transparent area as I did in my example, or try one of the other shape modes.  See: https://kivy.org/doc/stable/api-kivy.core.window.html#kivy.core.window.WindowBase.shape_mode

I would recommend getting the example I shared working before trying the other shape modes.

**Comment by rcnn-retall** [comment]
@ElliotGarbus Take a look, I have two doubts, that is, the window can not move the position, and why this will quit running on its own
![image](https://github.com/user-attachments/assets/a3b76946-19c7-4e7b-8eea-76c6a791e5f6)
![image](https://github.com/user-attachments/assets/20062710-f45f-4b20-81c8-e5ed4580c70f)

**Comment by ElliotGarbus** [comment]
@rcnn-retall Read the error message, you have set the shape mode to binAlpha.  It needs to be binalpha, all small letters.

If you want to drag the window around, you would need to write the code to capture the drag movement using the on_touch methods, and use them to change the Window position.

I suggest moving this discussion to one of the support forums.  The github issues is for reporting bugs or feature requests.
The Kivy Discord: https://discord.com/invite/eT3cuQp
Kivy User Support: https://groups.google.com/g/kivy-users
Reddit Kivy subreddit: https://www.reddit.com/r/kivy/

**Comment by rcnn-retall** [comment]
@ElliotGarbus It can move,The image will quit running if it is too large
I would like to ask you how to multithread for a long time

**Comment by rcnn-retall** [comment]
> 阅读错误消息，您已将形状模式设置为 binAlpha。它必须是 binalpha，全是小写字母。
> 
> 如果要拖动窗口，则需要编写代码以使用 on_touch 方法捕获拖动移动，并使用它们来更改 Window 位置。
> 
> 我建议将此讨论移至其中一个支持论坛。github issues 用于报告 bug 或功能请求。 The Kivy Discord：https://discord.com/invite/eT3cuQp Kivy 用户支持：https://groups.google.com/g/kivy-users Reddit Kivy subreddit：https://www.reddit.com/r/kivy/

不好意思，我英语不大好，但是图片过大这个形状窗口会退出
Sorry, my English is not good, but the picture is too large this shape window will exit
而且这个窗口在安卓上没有效果。
And this window doesn't work on Android.
